language: php
php:
  - '7.4'
  - master

env:
  global:
  - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"


before_install:
  - composer clear-cache

install:
  - travis_retry composer update $DEFAULT_COMPOSER_FLAGS

before_script:
  - echo 'zend.assertions=1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'assert.exception=On' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  # Prepare build output directory
  - mkdir build

script:
  - vendor/bin/phpstan analyse
  - vendor/bin/phpunit --coverage-clover=build/coverage.xml

after_success:
  # Submit coverage report to codecov.io
  - bash <(curl -s https://codecov.io/bash)

# Tell Travis CI to monitor only 'master' branch
branches:
  only: master
